// frontend/react/src/pages/Login/Login.js
import React, {Component} from 'react';
import twitterLogo from '../../twitter.svg'
import './Login.css';

export default class Login extends Component {
    state = {
        username: ''
    };

    handleInputChange = (event) => {
        this.setState({
            username: event.target.value
        })
    }

    handleSubmit = (event) => {
        event.preventDefault();
        const { username } = this.state;
        if(!username){
            return;
        }
        localStorage.setItem('@GoTwitter:username', username)
        this.props.history.push('/timeline')
    }

    render(){
        return(
            <div className="login-wrapper">
                <img src={twitterLogo} alt="GoTwitter"/>
                <form onSubmit={this.handleSubmit} action="">
                    <input value={this.state.username} onChange={this.handleInputChange} type="text" placeholder="Nome De Usuario"/>
                    <button type="submit">Entrar</button>
                </form>
            </div>        
        );
    }
}

// frontend/vue/src/views/Login/Login.vue
<template>
    <div class="login-wrapper">
        <br><br>
        <br><br>
        <br><br>
        <img src="../../assets/twitter.svg" alt="GoTwitter">
        <form @submit.prevent="handleSubmit" action="">
            <input v-model="username" type="text" placeholder="Nome do Usuario">
        
            <button type="submit" @click="$router.push('/timeline')">
                Entrar
            </button>
           
        </form>
    </div>
</template>

<script>
export default {
    data() {
        return {
            username: "",
        }
    },
    methods:{
        handleSubmit(){
            if(!this.username){
                return;
            }
            localStorage.setItem('username', this.username);
        }
    }
}
</script>

<style scoped>

.login-wrapper {
    height: 100%;

    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}

.login-wrapper form {
    margin: 20px 0 0;
    width: 100%;
    max-width: 280px;

    display: flex;
    flex-direction: column;
    align-items: stretch;
}

.login-wrapper form input {
    background: #fff;
    border: 1px solid #ddd;
    border-radius: 5px;
    height: 44px;
    padding: 0 15px;
    font-size: 14px;
}

.login-wrapper form button {
    margin: 10px 0 0;
    background: #4bb0ee;
    border-radius: 5px;
    height: 44px;
    border: 0;
    color: #fff;
    font-weight: bold;
    cursor: pointer;
    font-size: 16px;
}

.login-wrapper form button:hover {
    background: #42a1db;
}
</style>
