// frontend/react/src/components/Tweet/Tweet.js
import React, { Component } from 'react'
import './Tweet.css';
import Like from '../../like.svg'
import Axios from 'axios';

export default class Tweet extends Component {

     handleLike = async () => {
        const { _id } = this.props.tweet
        await Axios.post(`likes/${ _id }`);
    }

    render(){
        const tweet = this.props;
        return(
            <li className="tweet">
                <strong>{tweet.author}</strong>
                <p>{tweet.content}</p>
                <button type="button" onClick="this.handleLike">
                    <img src={Like} alt="Like"/>
                    {tweet.likes}
                </button>
            </li>
        ); 
    }
}

// frontend/vue/src/components/Tweet/Tweet.vue
<template>
    <li class="tweet">
        <strong>{{ tweet.author }}</strong>
        <p> {{ tweet.content}} </p>
        <button type="button" @click="handleLike">
            <img src="../../assets/like.svg" alt="Like"> {{ tweet.likes }}
        </button>
    </li>
</template>

<script>
import axios from '../../services/Axios.js';
export default {
    props:{
        tweet:Object
    },
    methods:{
        async handleLike(){
            axios.post('likes/'+this.tweet._id);
        }
    }
}
</script>

<style>
.tweet {
  padding: 20px 20px 0;
  margin: 20px 0 0;
  border-top: 1px solid #eee;
}

.tweet:first-child {
  margin-top: 0;
  padding-top: 0;
  border: 0;
}

.tweet p {
  margin: 15px 0;
  font-size: 14px;
  line-height: 20px;
}

.tweet button {
  border: 0;
  background: transparent;

  display: flex;
  align-items: center;
  color: #697882;
  cursor: pointer;
}

.tweet button img {
  margin-right: 5px;
}

.tweet button:hover {
  opacity: 0.7;
}

</style>
