// frontend/react/src/pages/TimeLine/Timeline.js
import React, {Component} from 'react';
import './Timeline.css';
import twitterLogo from '../../twitter.svg'
import axios from '../../services/api.js';
import Tweet from '../../components/Tweet/Tweet.js'
import SocketIO from  'socket.io-client'

export default class TimeLine extends Component {
    state={
        tweets: [],
        newTweet:''
    }

    async componentDidMount(){
        this.subscribeToEvents()
        const response = await axios.get('/tweets');
        this.setState({
            tweets: response.data
        })
    }

    handleInputChange = (event) => {
        this.setState({
            newTweet: event.target.value
        })
    }

    subscribeToEvents = () => {
        const io = SocketIO('http://loclahost:3000');
        io.on('tweet', data => {
            this.setState({
                tweets:[ data, ...this.state.tweets]
            })
        });
        io.on('like', data => {
            this.setState({
                tweets: this.state.tweets.map(tweet => 
                    tweet._id === data._id ? data : tweet
                )
            })
        });
    }

    handleNewTweet = async (event) => {
        if(event.keyCode !== 13){
            return;
        }
        const content = this.state.newTweet;
        const author = localStorage.getItem("@GoTwitter:username");
        await axios.post('tweets',{ author, content })

        this.setState({newTweet: ''})
    }

    render(){
        return(
            <div className="timeline-wrapper">
                <img src={twitterLogo} height={24}/> 
                <form action="">
                    <textarea 
                        value={this.state.newTweet}
                        onChange={this.handleInputChange}
                        onKeyDown = {this.handleNewTweet}
                        placeholder="O Que está acontecendo ?"/>
                </form>
                <ul className="tweet-list">
                    { 
                        this.state.tweets.map(tweet => 
                            <Tweet key={tweet._id} tweet={tweet} /> 
                        )
                    }
                </ul>
            </div>
        );
    }
}

// frontend/vue/src/views/Timeline/Timeline.vue
<template>
    <div class="timeline-wrapper">
        <img src="../../assets/twitter.svg" height="24">
        <form action="">
            <textarea 
                name="tweet" 
                id="user-tweeet"
                v-model="newTweet"
                @keydown="handleNewTweet"
                placeholder="O que está acontecendo ?"/>
        </form>
        <ul class="tweet-list">
            <Tweet 
                v-for="item in tweets" 
                v-bind:key="item._id"
                :tweet="item"/>
        </ul>
    </div>
</template>

<script>
import axios from '../../services/Axios.js';
import SocketIO from 'socket.io-client';
import Tweet from '../../components/Tweet/Tweet.vue'
export default {
    data() {
        return {
            newTweet:"",
            tweets:[]
        }
    },
    components:{
        'Tweet':Tweet
    },
    methods:{
        handleNewTweet(event){
            if(event.keyCode === 13 && this.newTweet){
                let author = localStorage.getItem("username");
                let content = this.newTweet;
                axios.post("tweets",{ author, content })
                .then(response => {
                    
                });
                this.newTweet = '';
            }
        },
        subscribeToEvents(){
            const io = SocketIO("http://localhost:3000")
            io.on('tweet', data => {
                this.tweets = this.tweets.concat(data)
            });
            io.on('like', data => {
                this.tweets = this.tweets.map(tweet => {
                    tweet._id === data._id ? data : tweet
                });
            })
        },
        getTweets(){
            axios.get("/tweets")
            .then(response => {
                this.tweets = response.data;
            })
            .catch(err => {
                console.log(err);
            });
        }
    },
    created(){
        this.subscribeToEvents();
        this.getTweets();
    }
}
</script>

<style scoped>

.timeline-wrapper {
  width: 600px;
  margin: 50px auto;

  display: flex;
  flex-direction: column;
  align-items: stretch;
}

.timeline-wrapper form {
  width: 100%;
  background: #e9f1f6;
  padding: 20px;
  border-radius: 5px;
  margin: 30px 0;
}

.timeline-wrapper form textarea {
  border: 3px solid #d8e5ed;
  border-radius: 5px;
  font-size: 14px;
  padding: 15px;
  width: 100%;
  resize: none;
}

.tweet-list {
  list-style: none;
  color: #1c2022;
}

</style>
